<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('product_stocks', function (Blueprint $table) {
            $table->id();
            $table->string('variant_ids')->nullable()->comment('first one is color,rest is attribute values');
            $table->unsignedBigInteger('product_id');
            $table->string('name')->nullable()->comment('auto generated by attributes and colors');
            $table->string('sku')->nullable();
            $table->integer('current_stock')->default(0);
            $table->float('unit_price', 15, 2)->nullable();
            $table->timestamps();
            
            $table->foreign('product_id')->references('id')->on('products');
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('product_stocks');
    }
};
